import type { Metadata } from "next";
import { poppins, roboto, courgette } from "@/fonts/font";
import ClientRoot from "@/components/ClientRoot";
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/bootstrap-icons.css";
import "../../public/assets/css/animate.min.css";
import "../../public/assets/css/swiper-bundle.min.css";
import "../../public/assets/css/nice-select.css";
import "../../public/assets/css/boxicons.min.css";
import "../../public/assets/css/style.css";
import 'lightgallery/css/lightgallery.css';
import 'lightgallery/css/lg-zoom.css';
import 'lightgallery/css/lg-thumbnail.css';
import 'lightgallery/css/lg-video.css';
export const metadata: Metadata = {
  title: "Gofly - Tour & Travel Booking Website.",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/img/fav-icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body className={`${poppins.variable} ${roboto.variable} ${courgette.variable}`}>
        <ClientRoot>
          {children}
        </ClientRoot>
      </body>
    </html>
  );
}
